### ISSUE TITLE
extension to bge

### ISSUE THREAD

**Issue by LouisFoucard** [MasonMcGill/fauxton#1]
Ok I just saw that bge is indeed supported, but can't remove the post..

**Comment by MasonMcGill** [comment]
Yep! And in case anyone stumbles upon this and is curious:

You can make a `BlenderModule` that hooks a Python controller up to a sensor. You can then use `bge` from within the Python controller.

See also: [`BlenderModule` example](http://vision.caltech.edu/~mmcgill/fauxton/extend_blender.html).
